CREATE TABLE todos
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(255),
    done BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_todos PRIMARY KEY (id)
);